### ISSUE TITLE
circle for the bond query feature is not centered

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/openchemlib-js#63]
If you press `q` when over a bond there is a dialog box allowing to edit query features 

However the circle that represents the fact that this bond is special is not centered on the bond

![image](https://user-images.githubusercontent.com/1484241/49204822-5eca2d00-f3ad-11e8-8f22-f73fe0b0afc4.png)

You can test it online: https://cheminfo.github.io/openchemlib-js/dist/Editor.html

**Comment by lpatiny** [comment]
It must be related to the different behaviour between java and javascript. Java draw an ellipse and toe x, y value is the top left. while in javascript we specify the center.

**Comment by targos** [comment]
can you post links to the relevant source code?

**Comment by lpatiny** [comment]
Java:
* https://github.com/cheminfo/openchemlib-js/blob/ac1a763c91e55c5e9f4edc55182a55ba14c78f06/src/com/actelion/research/gwt/chemlib/com/actelion/research/chem/Depictor.java#L104-L106
* https://github.com/cheminfo/openchemlib-js/blob/master/src/com/actelion/research/gwt/chemlib/com/actelion/research/chem/Depictor2D.java#L125-L130

Javascript, centered based:
* https://github.com/cheminfo/openchemlib-js/blob/master/src/com/actelion/research/gwt/gui/viewer/GWTDepictor.java#L151-L160
* https://github.com/cheminfo/openchemlib-js/blob/master/src/com/actelion/research/gwt/chemlib/com/actelion/research/chem/SVGDepictor.java#L160-L168

**Comment by lpatiny** [comment]
Seems to me it is called from only one place that is common between java and javascript:
https://github.com/cheminfo/openchemlib-js/blob/master/src/com/actelion/research/gwt/chemlib/com/actelion/research/chem/AbstractDepictor.java#L707-L726

I guess the solution would be that for SVG and GWT depictor we add the radius.

**Comment by rufenerc** [comment]
I see the problem.
Give me some time I guess I can manage this.

**Comment by lpatiny** [comment]
@rufenerc Please could you also have a look at https://github.com/cheminfo/openchemlib-js/issues/62 and maybe comment on https://github.com/cheminfo/openchemlib-js/issues/65 ?

If you could also send me by email your new email address. I could not invite you for the workshop last time.

**Comment by rufenerc** [comment]
Fixed in commit 09edf53809e64bc7a7729c74b6afc043bec9f82a

**Comment by targos** [comment]
The issue is still present in the SVG depictor. I may have time to fix it tomorrow.

<img width="943" alt="img" src="https://user-images.githubusercontent.com/2352663/49330077-d785e080-f589-11e8-9ce7-3415f2f746d1.png">
